#!/bin/sh

# Exit on error
set -o errexit

usage() {
    echo "
Usage:
$0 [Options]

Examples:
$0 -d ecommerce                           (run as 'root', auth local: unix socket)
$0 -d ecommerce_test                      (run as 'root', auth local: unix socket)
"""
}

while getopts ":d:h:p:" option; do
    case "${option}" in
        d)
            db_name=${OPTARG}
            ;;
	h)
            host=${OPTARG}
            ;;
        p)
            port=${OPTARG}
            ;;
        *)
            usage
            exit 3
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "$db_name" ]; then
   usage
   exit 3
fi

db_dir_path=$(dirname "$0")

mysql_cmd="mysql --user=root"

if [ -n "$host" ]; then
    mysql_cmd="$mysql_cmd --host=$host"
fi

if [ -n "$port" ]; then
    mysql_cmd="$mysql_cmd -P $port"
fi

$mysql_cmd -e "SET NAMES utf8;"
$mysql_cmd -e "drop database if exists $db_name;"
$mysql_cmd -e "create database $db_name CHARACTER SET utf8;"
