#!/bin/sh

# Exit on error
set -o errexit

usage() {
    echo "
Usage:
$0 -d <db_name> [-h <host>] [-p <port>]

Example:
$0 -d ecommerce -h 127.0.0.1 -p 3306
"
}

while getopts ":d:h:p:" option; do
    case "${option}" in
        d) db_name=${OPTARG} ;;
        h) host=${OPTARG} ;;
        p) port=${OPTARG} ;;
        *) usage; exit 3 ;;
    esac
done
shift $((OPTIND-1))

if [ -z "$db_name" ]; then
   usage
   exit 3
fi

# mysql_cmd="mysql --user=root"
mysql_cmd="mysql --user=root --password=$MYSQL_PWD"

# Only add host if provided
[ -n "$host" ] && mysql_cmd="$mysql_cmd --host=$host"
[ -n "$port" ] && mysql_cmd="$mysql_cmd -P $port"

# Use MYSQL_PWD for password-less login (CI)
$mysql_cmd -e "SET NAMES utf8;"
$mysql_cmd -e "DROP DATABASE IF EXISTS \`$db_name\`;"
$mysql_cmd -e "CREATE DATABASE \`$db_name\` CHARACTER SET utf8;"
