name: CI

on:
  push:
    branches: [ main, master ]  # Trigger on 'main and master' branch
  pull_request:
    branches: [ main, master ]  # Trigger on PR to 'main and master'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: ecommerce
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..100}; do
            if mysql -h127.0.0.1 -utestuser -ptestpass -e "SELECT 1" > /dev/null 2>&1; then
              echo "MySQL is ready!"
              break
            fi
            echo "⏳ Waiting for MySQL..."
            sleep 5
          done

      - name: Build with Maven
        run: mvn clean verify