name: CI Pipeline

on:
  push:
    branches: [ main ]  # Trigger on 'main' branch
  pull_request:
    branches: [ main ]  # Trigger on PR to 'main'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest  # Use GitHub's default Ubuntu runner

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ecommerce
          MYSQL_DATABASE: ecommerce
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    container:
      image: maven:3.6.3-jdk-11  # Use Maven container (based on Debian Bullseye)

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Fix APT repositories and install MySQL client (for Debian Buster compatibility)
      - name: Fix apt repositories for buster (archive)
        run: |
          # Replace 'deb.debian.org' with 'archive.debian.org' for buster
          sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list
          sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list
          
          # Disable expired key check for archived repositories
          apt-get -o Acquire::Check-Valid-Until=false update -y
          apt-get install -y default-mysql-client
          apt-get install -y net-tools

      # Step 3: Recreate database
      - name: Recreate database
        run: |
          export MYSQL_PWD=ecommerce
          chmod +x db/creation/recreate_everything
          db/creation/recreate_everything -d ecommerce -h 127.0.0.1 || echo "DB script failed or skipped"
          netstat -plnt | grep 3306
          mysql -uroot -pecommerce

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..100}; do
            if mysql -h127.0.0.1 -uroot -pecommerce -e "SELECT 1" > /dev/null 2>&1; then
              echo " MySQL is ready!"
              break
            fi
            echo " Waiting for MySQL..."
            sleep 5
          done
