name: CI Pipeline

on:
  push:
    branches: [ main ]  # Trigger on 'main' branch
  pull_request:
    branches: [ main ]  # Trigger on PR to 'main'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest  # Use GitHub's default Ubuntu runner

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: ecommerce
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass

    container:
      image: maven:3.6.3-jdk-11  # Use Maven container (based on Debian Bullseye)

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Fix APT repositories and install MySQL client (for Debian Buster compatibility)
      - name: Fix apt repositories for buster (archive)
        run: |
          # Replace 'deb.debian.org' with 'archive.debian.org' for buster
          sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list
          sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list
          
          # Disable expired key check for archived repositories
          apt-get -o Acquire::Check-Valid-Until=false update -y
          apt-get install -y default-mysql-client
          apt-get install -y net-tools

      # Recreate database
      - name: Recreate database
        run: |
          export MYSQL_PWD=testpass
          echo "DB creation OK ......"
          netstat -plnt | grep 3306
          echo "netstat : OK ......"
          mysql -uroot -ptestpass
          echo "DB connect OK ........"
          SHOW DATABASES
